ALTER TABLE users ALTER COLUMN login SET NOT NULL;
ALTER TABLE users ALTER COLUMN api_token SET NOT NULL;

ALTER TABLE frames ALTER COLUMN start_at SET NOT NULL;
ALTER TABLE frames ALTER COLUMN end_at SET NOT NULL;
ALTER TABLE frames ALTER COLUMN project_id SET NOT NULL;

ALTER TABLE projects ALTER COLUMN name SET NOT NULL;
ALTER TABLE projects ALTER COLUMN user_id SET NOT NULL;
