// flow-typed signature: 6f93fc08b4d359936a3bd4852532ab1a
// flow-typed version: <<STUB>>/material-ui-chip-input_v^0.14.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui-chip-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui-chip-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui-chip-input/lib/ChipInput' {
  declare module.exports: any;
}

declare module 'material-ui-chip-input/src/ChipInput' {
  declare module.exports: any;
}

declare module 'material-ui-chip-input/stories/ClipboardExample' {
  declare module.exports: any;
}

declare module 'material-ui-chip-input/stories/ControlledChipInput' {
  declare module.exports: any;
}

declare module 'material-ui-chip-input/stories/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui-chip-input/lib/ChipInput.js' {
  declare module.exports: $Exports<'material-ui-chip-input/lib/ChipInput'>;
}
declare module 'material-ui-chip-input/src/ChipInput.js' {
  declare module.exports: $Exports<'material-ui-chip-input/src/ChipInput'>;
}
declare module 'material-ui-chip-input/stories/ClipboardExample.js' {
  declare module.exports: $Exports<'material-ui-chip-input/stories/ClipboardExample'>;
}
declare module 'material-ui-chip-input/stories/ControlledChipInput.js' {
  declare module.exports: $Exports<'material-ui-chip-input/stories/ControlledChipInput'>;
}
declare module 'material-ui-chip-input/stories/index.js' {
  declare module.exports: $Exports<'material-ui-chip-input/stories/index'>;
}
